# -*- coding: utf-8 -*-
"""A gene expression signature classifying telomerase and ALT immortalization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mC67ZCTjyPbncHpOHogxY-l2r4Ls5cKs

## A gene expression signature classifying telomerase and ALT immortalization

### Data Cleaning
1. Import libraries
"""

import pandas as pd

"""2. Mount Drive
3. Upload the file
"""

# Commented out IPython magic to ensure Python compatibility.
# Mount Google Drive
#Make sure to run the cell that mounts Google Drive first, and then navigate to the directory where your file is located
from google.colab import drive
drive.mount('/content/drive')

# Change the working directory to where your file is located
# %cd /content/drive/MyDrive/Documents/

telomere_data = pd.read_csv('/content/drive/MyDrive/Documents/Telomere.csv')

# Display the first few rows of the DataFrame to inspect the data
print(telomere_data.head())

"""4. Drop and rename columns

We have several 'names' for each column, let's drop them
"""

# Drop unnecessary rows
telomere_data = telomere_data.drop([0, 1, 2])

print(telomere_data.head())

# Reset the index after dropping rows
telomere_data = telomere_data.reset_index(drop=True)

new_column_names = [
    'Samples','ALT_lung_1', 'ALT_lung_2', 'ALT_lung_3', 'ALT_lung_4', 'ALT_lung_5', 'ALT_lung_6', 'ALT_liver_1', 'ALT_liver_2',
    'Tel_ovarian_1', 'Tel_ovarian_2', 'Tel_bladder_1', 'Tel_bladder_2', 'Tel_cervical_1', 'Tel_cervical_2',
    'Tel_fibosarcoma_1', 'Tel_fibosarcoma_2', 'hMSC_1', 'hMSC_2', 'hMSC_3', 'hMSC_4', 'hMSC_5', 'hMSC_6', 'hMSC_7',
    'hMSC_8', 'normal_lung_1', 'normal_lung_2', 'normal_lung_3', 'normal_lung_4', 'hMSC_9', 'hMSC_10', 'hMSC_11',
    'hMSC_12', 'hMSC_13', 'hMSC_14', 'hMSC_15', 'hMSC_16', 'Liposarcoma_ALT_1', 'Liposarcoma_ALT_2', 'Liposarcoma_ALT_3',
    'Liposarcoma_ALT_4', 'Liposarcoma_ALT_5', 'Liposarcoma_ALT_6', 'Liposarcoma_ALT_7', 'Liposarcoma_ALT_8', 'Liposarcoma_ALT_9',
    'Liposarcoma_ALT_10', 'Liposarcoma_Tel_1', 'Liposarcoma_Tel_2', 'Liposarcoma_Tel_3', 'Liposarcoma_Tel_4', 'Liposarcoma_Tel_5',
    'Liposarcoma_Tel_6', 'Liposarcoma_Tel_7', 'Liposarcoma_Tel_8'
]

# Assign new column names
telomere_data.columns = new_column_names

print(telomere_data.head())

telomere_data.head()

"""5. Null values"""

#Let's check for null values
telomere_data.isnull().any()

# Drop null values
telomere_data_cleaned = telomere_data.dropna()

#Let's check again for null values
telomere_data_cleaned.isnull().any()

#General info
telomere_data_cleaned.info()

#Find duplicates
telomere_data_cleaned.duplicated()

"""### Exploratory Data Analysis (EDA)"""

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

telomere_data_cleaned.head()

# Drop the columns with all NaN values
telomere_data_cleaned = telomere_data_cleaned.dropna(axis=1, how='all')

telomere_data_cleaned.head()

telomere_data_cleaned.info()

# Save the cleaned dataframe to a CSV file
telomere_data_cleaned.to_csv('/content/telomere_data_cleaned.csv', index=False)

from google.colab import files

# Generate a download link
files.download('/content/telomere_data_cleaned.csv')

"""A general overview of the data"""

telomere_data_cleaned.info()